matrix:
  include:
    - language: scala
      scala:
         - 2.12.2
      services:
        - docker
      before_install:
         - docker pull postgres:9.6
      before_script:
        - cd server
      script:
        - sbt clean coverage test coverageReport
      after_success:
        - sbt coverageAggregate codacyCoverage

    - language: node_js
      node_js:
        - 8.14.0
      before_script:
      - cd web-ui
      - npm install -g @angular/cli
      - npm install -g @angular-devkit/build-angular
      - npm install
      script:
      - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
