---
- hosts: xsnd
  gather_facts: no
  roles:
    - ubuntu-16-04
    - node

  vars:
    - node_user: xsn
    - node_group: xsn
    - node_data_folder: '.xsncore'
    - node_download_url: https://github.com/X9Developers/XSN/releases/download/v1.0.21/xsn-1.0.21-x86_64-linux-gnu.tar.gz
    - node_download_checksum: sha1:df5733011870de555c548ae303d18ef1f8bd5058
    - node_compressed_file: /home/ubuntu/xsn.tar.gz
    - node_daemon_file: xsn-1.0.21/bin/xsnd
    - node_config_file: config/nodes/xsn.conf
    - node_config_filename: xsn.conf
    - node_executable: xsnd
    - node_service_name: xsn-rpc
