---
- hosts: server
  gather_facts: no
  roles:
    - ubuntu-16-04
    - explorer

  vars:
    explorer_config_file: 'config/explorer/bitcoin-explorer.env'
    explorer_service_name: 'bitcoin-backend'
